Repository goabstract/go-git, pull requests merged in 2020-02, with the labels that each got.

#7 feat(fetch): allow fetching older commits in shallow repo
  remote.go
  remote_test.go
Labels: target/fork-4.13.1

#10 refactor(fetch): properly report shallow commits
  remote.go
Labels: target/release-4.x.x

#13 feat(repack): optimizes repack to prefetch data
  plumbing/format/packfile/delta_breaker.go
  plumbing/format/packfile/delta_selector.go
Labels: backport, release-4.x.x
